### ISSUE TITLE
Add social icons to banner on main page and About Us page

### ISSUE THREAD

**Issue by hola-soy-milk** [distributeaid/distributeaid.org#117]
CodeSee recording:
https://app.codesee.io/shared/4bb1a720-5912-11ec-92c1-f7ca5b5ec43b

Figma design:
![Screenshot of Figma design showing social icons in banner](https://user-images.githubusercontent.com/656318/145444289-08656f07-52e9-4bf9-bced-19d402196bc2.png)

Figma design for reference:
https://www.figma.com/file/Ey8xRnstZS4UYmqQwyYZdC/Landing-Page?node-id=208%3A601

> NOTE: [SocialIconContainer](https://github.com/distributeaid/distributeaid.org/blob/saga/src/components/socials-container/SocialIconContainer.tsx) has the icons imported

**Comment by RabeaGleissner** [comment]
I'll add these :)

**Comment by hola-soy-milk** [comment]
Wonderful, thank you so much!

**Comment by RabeaGleissner** [comment]
@ramonh @deammer I'm wondering if one of you could help me with some questions!

I saw that we still have the old social icons in the footer but they're not in the design. I assume we need to get rid of the icons in the footer? Or do we want to keep both? In that case we should probably stick to one icon design (the blue and white one?).

I saw the note in Figma saying that the icons should only show on wider breakpoints and be hidden on mobile. We could make it so that on mobile the icons are visible in the footer instead?

Hope you can help!

**Comment by hola-soy-milk** [comment]
Good questions, thank you!

In my opinion, we could leave these in for now, as they're not occupying much space. What do you think?

**Comment by RabeaGleissner** [comment]
Sure, happy to keep them but I think I will change the icons to the new blue and white design to make it consistent. And at the moment we only have Twitter, LinkedIn and Instagram in the footer, so I might add Facebook in there as well.

Hope that's ok!

**Comment by hola-soy-milk** [comment]
That sounds marvelous, I'm all for consistency, thank you!

**Comment by RabeaGleissner** [comment]
Done!
