### ISSUE TITLE
Setup Jest For Testing

### ISSUE THREAD

**Issue by jtfairbank** [distributeaid/distributeaid.org#4]
https://jestjs.io/

Haven't had time to setup testing yet- making sure this combo of tools works well for the team first.  Anyone can pick this up in the meantime!

**Comment by iulspop** [comment]
Hi @jtfairbank, I'm interested in picking up this issue. I'm doing a course on testing javascript by Kent C. Dodds, so this is good practice for me!

I'm just wondering, what functionality do you want to test with jest right now? Jest is used for integration or unit tests. In the context of React, you'd write tests for a group of components working together or for a single component. Judging from the `src/components/` folder, there don't seem to be components worth testing for the increase in confidence right now.

It would be better value to setup e2e tests with Cypress right now. Since, they could give a lot of confidence that the website is working as desired and with perhaps less complexity than adding component tests with Jest.

**Comment by khendrikse** [comment]
Hey @jtfairbank I'd love to write some tests to help out, but I need

```
   - Space ID,
    - Content Delivery API Token
    - Content Preview API Token
    - (optional) Content Management API Personal Access Token
``` 

:) any way to get that?
