### ISSUE TITLE
Mobile view has padding on the right 

### ISSUE THREAD

**Issue by coderbyheart** [distributeaid/distributeaid.org#563]
![Screenshot_2022-08-31-08-54-22-03_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/188915/187613050-0420111e-cf5c-4809-9b0b-9b8912b166c1.jpg)

**Comment by Pathholder1806** [comment]
Hey @coderbyheart !
I would like to work on the issue

As I can observe the issue is occurring at width below 400px

**Comment by Pathholder1806** [comment]
As I can observe the issue is occurring at width below 300px

**Comment by Pathholder1806** [comment]
Hey @coderbyheart !
I think adding a new media query in 'index.css' for widths below 400px and positioning the **body** as absolute under it is solving the issue.

**Comment by coderbyheart** [comment]
I'd rather you fix the size of the component that is too wide:

![image](https://user-images.githubusercontent.com/188915/187694319-6cc823c3-e380-487c-85cd-ef906db6ddb1.png)

**Comment by fosa-ij** [comment]
Hey is anyone currently on this issue?

**Comment by jtfairbank** [comment]
Hey @Pathholder1806 I've assigned the issue to you!

This is occurring because the 3D globe visualization requires an explicit width set to render.  I've made a [CodeSee map](https://app.codesee.io/maps/public/e491e600-2976-11ed-a948-5baa68eecc2f) highlighting the relevant files.

You'll probably need to use javascript in the `shipments-on-globe.tsx` visualization component to set a smaller width / height if the viewport width is smaller then 400px or so.  You can also see if there are any ways to set the width dynamically by looking at the [react-globe.gl library documentation](https://github.com/vasturiano/react-globe.gl).  For example, if it's possible to set it to 100% of the container and then use [Tailwind's responsive classes](https://tailwindcss.com/docs/responsive-design) to set the container's width.

Finally, please don't forget to add your name to the `/CONTRIBUTORS.md` file which is a requirement for first-time contributors.  If you need some help with this one, drop by one of our [Code Jams](https://twitter.com/DistributeAid/status/1565079810740723716?s=20&t=j60PBwJKxZZ4q1ywrOY0Gg)!

**Comment by jtfairbank** [comment]
Hey @fosa-ij!  It looks like @Pathholder1806 wanted to take it, so I want to give them a chance first.  But maybe you two can jump on a zoom to collaborate on it?

We'll be adding more issues soon!  Our maintainers temporarily overwhelmed with all the love and support from the 100devs community, give us a few days and then check back in to find another issue to contribute to?

**Comment by fosa-ij** [comment]
Okay @jtfairbank I'd definitely check again 
Thanks a lot 👍

**Comment by mabioIa** [comment]
Sorry, didn't notice that this issue was taken.

**Comment by mrxvt** [comment]
Sorry about the fix collision. Let me know if I should close the PR.

**Comment by jtfairbank** [comment]
Hey @mabioIa no worries!  I commented on the PR as well but yeah, I think that'd be best for now to give @Pathholder1806 a few days to work on a solution for it.

We'll have more issues up soon so check back in later this week!  We recommend commenting on an issue that you're interested in taking it, and we'll assign it to you so that others can see you're working on it to prevent this confusion.

Really appreciate your interested in contributing to DA though, love the energy and excitement!

**Comment by mrxvt** [comment]
Happy to help @jtfairbank.

**Comment by Pathholder1806** [comment]
Hey @jtfairbank 
Thanks for the consideration! I'll be trying my best to solve this issue ASAP.
Will surely connect with you in case of any problem.

**Comment by Pathholder1806** [comment]
Hey @jtfairbank
I have created a PR with my solution to the error. Kindly review it!
Also If have highlighted another issue in the **index.css**. Kindly take a look into it too.
