### ISSUE TITLE
First yarn install takes very long

### ISSUE THREAD

**Issue by hola-soy-milk** [distributeaid/distributeaid.org#821]
### What happened?

Tried cloning the app from scratch and running yarn install.

Took about 5 minutes on a M1 macbook pro with decent internet connection

### Steps to reproduce

1. Clone the project
2. Run yarn install

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtfairbank** [comment]
Looking through our `package.json` file and we might be able to remove the following packages.  If anyone wants to pick up on this I'd recommend going through removing 1 group of packages at a time with `yarn remove packageName` and making sure the tests still work (`yarn test` and `yarn test:e2e`).  Make sure he dev server is on when you run the end-2-end tests!

* `@types/lodash` and `lodash`
* `@types/node`
* `@types/react-table`, `react-table`, and `/src/types/react-table-config.d.ts`
* `react-hook-form`
* `react-multi-carousel`
* `sharp`?? (since we're using `gatsby-image-sharp` and not `sharp` directly)
* `@graphql-codegen/cli`, `@graphql-codegen/typescript`, and `@graphql-codegen/typescript-document-nodes`
* `netlify-cli`

**Comment by JasonFritsche** [comment]
I'll take this one!

**Comment by JasonFritsche** [comment]
I'll take this one!

**Comment by jtfairbank** [comment]
Thanks so much @JasonFritsche!  Hope you had a great Thanksgiving (if you celebrate). :smile:

**Comment by JasonFritsche** [comment]
@jtfairbank Can you please describe the steps to run end-to-end tests locally? Thank you.

**Comment by JasonFritsche** [comment]
@jtfairbank disregard. I was having an issue with the `HOSTNAME` on my machine. Temporarily hardcoded 'localhost' in the `baseUrl` in `testHosts.ts`. Seems to be working.

**Comment by jtfairbank** [comment]
Hey @JasonFritsche sorry for the delay in getting back to you!  Glad you found a temporary workaround.

What I usually do for the E2E tests is run the dev server, then on another terminal run the tests.  If that's not working for you then it'd be helpful to file a bug with more details (OS, console output, etc) so we can investigate. 

Sounds like `HOSTNAME` is an environment variable that's not set by default on your machine?  Or maybe your terminal config or another project is setting it to something non-standard?

**Comment by JasonFritsche** [comment]
I'm running Fedora 36. I'm able to [change my hostname](https://docs.fedoraproject.org/en-US/quick-docs/changing-hostname/). Unsure if this issue would happen on all Linux distro's. After I wrap up this story I'll do some research and see if we should make any changes.

**Comment by jtfairbank** [comment]
@JasonFritsche weird, I'm running Elemantary OS which is an Ubuntu 18.04 offshoot and things work just fine.

**Comment by JasonFritsche** [comment]
Weird indeed. I'll take a look after I PR this.

**Comment by JasonFritsche** [comment]
I've removed the following packages:
- `netlify-cli`
- `@graphql-codegen/cli`
- `@graphql-codegen/typescript`
- `@graphql-codegen/typescript-document-nodes`
- `sharp`
- `react-hook-form`
- `@types/node`
- `@types/testing-library__jest-dom`
- `@types/testing-library__react`
- `@types/react-table`
- `react-table`
- `react-multi-carousel`

I've added the following package:
- `ts-node` (Jest dependency)

Install times (starting with no `node_modules` and no `yarn.lock`) on my machine:
- Before: 3m 15s
- After 2m 37s

**Comment by JasonFritsche** [comment]
Hey all. Apologies for the delay on wrapping this up. I have Covid, it kicked my butt pretty much all weak. I'm back at it today though, working on wrapping this up rn.
